# All animated
Backgrounds = [("Medieval", 5),
               ("Mount-Fuji", 5),
               ("Talladega", 5),
               ("The-Moon", 5)
               ]


# All animated
Effects = [("Hot-Head", 5),
           ("None", 95)
           ]


# Static
Skins = [("Blk", 10),
         ("Olive", 10),
         ("Tan", 10),
         ("White", 10),
         ("Alien", 5),
         ("Devil", 5),
         ("Monke", 5),
         ("Vampire", 5),
         ("None", 0)
        ]


# Static
Shirts = [("Artist", 10),
          ("ButtonUp-Blue", 10),
          ("ButtonUp-Green", 10),
          ("ButtonUp-Orange", 10),
          ("ButtonUp-Purple", 10),
          ("ButtonUp-Red", 10),
          ("ButtonUp-White", 10),
          ("ButtonUp-Yellow", 10),
          ("CollegeSweater-Blue", 10),
          ("CollegeSweater-Grey", 10),
          ("CollegeSweater-Red", 10),
          ("FakeBusinessHoody", 10),
          ("Flannel-Blue", 10),
          ("Flannel-Green", 10),
          ("Flannel-Grey", 10),
          ("Flannel-Orange", 10),
          ("Flannel-Purple", 10),
          ("Flannel-Red", 10),
          ("Flannel-White", 10),
          ("Flannel-Yellow", 10),
          ("HawaiianShirt-Bananas", 10),
          ("HawaiianShirt-FlowerBloom", 10),
          ("HawaiianShirt-FlowerBlossom", 10),
          ("HawaiianShirt-FlowerStems", 10),
          ("HawaiianShirt-PalmBird", 10),
          ("HawaiianShirt-Palms", 10),
          ("Hoody-Black", 10),
          ("Hoody-Blue", 10),
          ("Hoody-Green", 10),
          ("Hoody-Orange", 10),
          ("Hoody-Pink", 10),
          ("Hoody-Purple", 10),
          ("Hoody-Red", 10),
          ("Hoody-White", 10),
          ("Hoody-Yellow", 10),
          ("Jersey-Altura", 10),
          ("Jersey-AlturaDeluxe", 10),
          ("Jersey-BlackAndYellow", 10),
          ("Jersey-GreenAndGold", 10),
          ("Jersey-LightblueAndOrange", 10),
          ("Jersey-NavyandWhite", 10),
          ("Jersey-OrangeAndWhite", 10),
          ("Jersey-PurpleAndGold", 10),
          ("Jersey-RedAndWhite", 10),
          ("Jersey-White", 10),
          ("Jersey-YellowAndGreen", 10),
          ("MarcoShirt-Black", 10),
          ("MarcoShirt-Blue", 10),
          ("MarcoShirt-Green", 10),
          ("MarcoShirt-Orange", 10),
          ("MarcoShirt-Purple", 10),
          ("MarcoShirt-Red", 10),
          ("MarcoShirt-White", 10),
          ("MarcoShirt-Yellow", 10),
          ("NoShirt", 10),
          ("Sweater-Black", 10),
          ("Sweater-Blue", 10),
          ("Sweater-Green", 10),
          ("Sweater-Grey", 10),
          ("Sweater-Mustard", 10),
          ("Sweater-Orange", 10),
          ("Sweater-Purple", 10),
          ("Sweater-Red", 10),
          ("Sweater-Seafoam", 10),
          ("Tanktop-BlackSweat", 10),
          ("Tanktop-BlueStipes", 10),
          ("Tanktop-GreyMustard", 10),
          ("Tanktop-Murica", 10),
          ("Tanktop-Red", 10),
          ("Tanktop-TealTime", 10),
          ("Tanktop-White", 10),
          ("Tanktop-WhiteStained", 10),
          ("Tshirt-Black", 10),
          ("Tshirt-Blue", 10),
          ("Tshirt-Dinosaur", 10),
          ("Tshirt-Green", 10),
          ("Tshirt-Orange", 10),
          ("Tshirt-Overpriced", 10),
          ("Tshirt-Planet", 10),
          ("Tshirt-Purple", 10),
          ("Tshirt-Red", 10),
          ("Tshirt-White", 10),
          ("Tshirt-Yellow", 10),
]

# Static
Legs = [("JeansBelt", 5),
        ("Jorts", 5),
        ("KhakisBelt", 5),
        ("NoPants", 5),
        ("PantsBelt-Black", 5),
        ("PantsBelt-Camo", 5),
        ("PantsBelt-Green", 5),
        ("PantsBelt-LightBlue", 5),
        ("PantsBelt-Orange", 5),
        ("PantsBelt-Pink", 5),
        ("PantsBelt-Purple", 5),
        ("PantsBelt-Red", 5),
        ("PantsBelt-White", 5),
        ("Shorts-Black", 5),
        ("Shorts-Camo", 5),
        ("Shorts-Green", 5),
        ("Shorts-Khaki", 5),
        ("Shorts-LightBlue", 5),
        ("Shorts-Orange", 5),
        ("Shorts-Pink", 5),
        ("Shorts-Purple", 5),
        ("Shorts-Red", 5),
        ("Shorts-White", 5),
        ("SweatPants-Black", 5),
        ("SweatPants-Blue", 5),
        ("SweatPants-Grey", 5),
        ("SweatPants-Red", 5)
]

# Static
Shoes = [("NewBalance", 0),
         ("None", 1)
]

# Static
Hats = [("Afro", 5),
        ("Bandana", 5),
        ("BaseballCap", 5),
        ("BeerHat", 5),
        ("Bowl", 5),
        ("BucketHat", 5),
        ("Cowpoke", 5),
        ("CrossCut", 5),
        ("CurlyTop", 5),
        ("DadRock", 5),
        ("Einstein", 5),
        ("Emo", 5),
        ("Fauxhawk", 5),
        ("Fedora", 5),
        ("Fez", 5),
        ("FlamingBuffalo", 5),
        ("Football", 5),
        ("HardHat-Yellow", 5),
        ("HighTop", 5),
        ("Lockes", 5),
        ("LumberJack", 5),
        ("MalePattern", 5),
        ("Monk", 5),
        ("Morpher", 5),
        ("Napoleon", 5),
        ("Ninja", 5),
        ("None", 5),
        ("NuclearSafetyInspector", 5),
        ("PartyHat", 5),
        ("Pirate", 5),
        ("Ponytail", 5),
        ("PorkPie", 5),
        ("RicePaddy", 5),
        ("SlickedBack", 5),
        ("SpaceScientist", 5),
        ("StrawHat", 5),
        ("TheVeryBest", 5),
        ("TopHat", 5),
        ("Ushanka", 5),
        ("Viking", 5)
]

# Static
Faces = [("ClassicHero-Black", 6),
         ("ClassicHero-Blue", 6),
         ("ClassicHero-Green", 6),
         ("ClassicHero-Orange", 6),
         ("ClassicHero-Purple", 6),
         ("ClassicHero-Red", 6),
         ("ClassicHero-White", 6),
         ("ClassicHero-Yellow", 6),
         ("DiamondVision", 10),
         ("Glasses", 10),
         ("HockeyFan", 10),
         ("Majora", 10),
         ("PropaneKing", 10),
         ("Society", 10),
         ("StraightShades", 10),
         ("Sunglasses-Blue", 10),
         ("SunGlasses-Green", 10),
         ("Sunglasses-Orange", 10),
         ("Sunglasses-Purple", 10),
         ("SunGlasses-Red", 10),
         ("SunGlasses-Yellow", 10),
         ("None", 20),
]

# Static
Items = [("80sCellPhone", 10),
         ("AuGun", 10),
         ("BagOMoney", 10),
         ("BananaPeeled", 10),
         ("BananaUnpeeled", 10),
         ("BeerCan", 10),
         ("Cheeseburger", 10),
         ("CoffeeMug-Black", 10),
         ("CoffeeMug-White", 10),
         ("Corndog", 10),
         ("EnergyDrink", 10),
         ("HotDog", 10),
         ("JuiceBox", 10),
         ("Machete", 10),
         ("MacheteForCrime", 10),
         ("Martini", 10),
         ("None", 10),
         ("Ramen", 10),
         ("RealLaserSword-Blue", 10),
         ("RealLaserSword-Green", 10),
         ("RealLaserSword-Purple", 10),
         ("RealLaserSword-Red", 10),
         ("Revolver", 10),
         ("RootBeer2", 10),
         ("RootBeerMug", 10),
         ("Sandwich", 10),
         ("Spatula", 10),
         ("SuperbSoaker-Blue", 10),
         ("SuperbSoaker-Green", 10),
         ("SuperbSoaker-Orange", 10),
         ("SuperbSoaker-Purple", 10),
         ("SuperbSoaker-Red", 10),
         ("SuperbSoaker-Yellow", 10),
         ("Swashbuckler", 10),
         ("Tomahawk", 10),
         ("TomahawkSteakCooked", 10),
         ("TomahawkSteakRaw", 10),
         ("ToyLaserSword-Blue", 10),
         ("ToyLaserSword-Green", 10),
         ("ToyLaserSword-Purple", 10),
         ("ToyLaserSword-Red", 10),
         ("Tumbler", 10),
         ("WaterBalloon-Blue", 10),
         ("WaterBalloon-Green", 10),
         ("WaterBalloon-Orange", 10),
         ("WaterBalloon-Purple", 10),
         ("WaterBalloon-Red", 10),
         ("WaterBalloon-Yellow", 10),
         ("WaterBottle", 10),
         ("WholeBitcoin", 10),
         ("Yorick", 10)
]

# All animated
Mowers = [("Red", 45),
          ("Green", 45),
          ("DarkGreen", 45),
          ("Orange", 30),
          ("Yellow", 30),
          ("Blue", 15),
          ("Brown", 15),
          ("White", 15),
          ("Black", 15),
          ("LightBlue", 15),
          ("Maroon", 15),
          ("Pink", 15),
          ("Purple", 15),
          ("RedOrange", 15),
          ("Seafoam", 15),
          ("Teal", 15),
          ("Copper", 4),
          ("Silver", 3),
          ("Golden", 2),
          ("Diamond", 1),
          ("Rainbow", 1),
          ]

# All animated
MowerEffects = [("Flames", 10),
                ("Shine", 10),
                ("None", 80)
                ]

